name: Generate Mavlink Headers

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch to compile and push'
        required: true
        default: 'master'

jobs:
  generate-headers:
    runs-on: ubuntu-22.04

    steps:
      - name: Determine target branch
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "TARGET_BRANCH=master" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.source_branch }}" == "master" ]; then
            echo "TARGET_BRANCH=master" >> $GITHUB_ENV
          else
            echo "TARGET_BRANCH=feature/${{ github.event.inputs.source_branch }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'push' && 'master' || github.event.inputs.source_branch }}
          path: mavlink
      - uses: actions/checkout@v4
        with: 
          repository: rosflight/mavlink_c_library
          path: mavlink_c_library
          ref: 'master'

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Install Python2.7
        run: sudo apt update && sudo apt install python2.7 -y

      - name: Generate message headers
        run: |
          cd mavlink
          python2.7 -m pymavlink.tools.mavgen -o ../mavlink_c_library --lang C message_definitions/v1.0/rosflight.xml 

      - name: Push message headers to mavlink_c_library
        run: |
          cd mavlink_c_library
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote add target git@github.com:rosflight/mavlink_c_library.git
          git checkout -B $TARGET_BRANCH
          git push --set-upstream target $TARGET_BRANCH
          git commit -am "${{ github.event.head_commit.message }}"
          git push target --all
